model:
  tmix: qwerky7
  attention_type: rwkv7_wind_backstepping_bighead # default set to existing kernel sources in rwkv_cuda_wind/
  reinit_att: 0
  gate_rank_type: 2
  use_pos_emb: 1
  balance_state: 0
  groupnorm_att: 1
